spring.application.name=repopulse
server.port=${PORT:8080}

spring.datasource.url=${DB_URI}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PWD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

openrouter.api.key=${OPENROUTER_KEY}
openrouter.model=openai/gpt-4o-mini

google.client.id=${GOOGLE_CLIENT_ID}